In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle as pkl
import os
import tensorflow as tf

2024-12-04 14:14:57.190677: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1733318097.206126   11992 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733318097.210978   11992 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-04 14:14:57.224453: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Model size

In [28]:
model_tflite_size = os.path.getsize('qat_model.tflite')/(1024**2)
model_original_size = sum(os.path.getsize(os.path.join(dirpath, filename)) for dirpath, _, filenames in os.walk('original_model') for filename in filenames)/(1024**2)

In [30]:
print(f"Original model size: {model_original_size:.2f} MB")
print(f"Quantized model size: {model_tflite_size:.2f} MB")

Original model size: 119.30 MB
Quantized model size: 9.91 MB


### Performance metrics

In [6]:
# open pickle file
with open('results.pkl', 'rb') as f:
    data = pkl.load(f)

In [7]:
data.keys()

dict_keys(['y_col', 'y_fire', 'y_steer', 'pred_col', 'pred_fire', 'pred_steer'])

In [20]:
data['pred_steer']

array([[0.01746561],
       [0.01746561],
       [0.01746561],
       ...,
       [0.01746561],
       [0.01746561],
       [0.01746561]], dtype=float32)

In [21]:
data['y_steer']

array([       nan,        nan,        nan, ..., 0.00851306,        nan,
              nan], dtype=float32)

In [17]:
data['pred_steer']

# count the values of data['pred_col'], the np array
np.unique(data['pred_steer'], return_counts=True)

(array([0.01746561, 0.01746561], dtype=float32), array([  10, 5344]))